### PR TITLE
fix: tolerate method- and property-style Address.address

### PR DESCRIPTION
**Pull request by vstakhov**
## Problem

Same root cause as haraka/haraka-plugin-rspamd#59. The Address objects in mail/rcpt hook params come from the host Haraka, and the two parsers in circulation expose `address` differently:

- `@haraka/email-address` (Haraka >= 3.2.0): `address` is a string property
- `address-rfc2821` (every released Haraka <= 3.1.7): `address()` is a method

Since v1.3.0 (#42) the plugin reads `params?.[0]?.address` as a property, so on Haraka <= 3.1.7 it gets the accessor function instead of the address string:

- `mail_from_access` / `rcpt_to_access`: `in_list()` throws `TypeError: address.toLowerCase is not a function` on every check (Haraka logs the plugin exception and continues), so whitelist and blacklist entries are silently never honored
- `any_whitelist`: the `!email` whitelist lookup can never match

The pre-1.3.0 form `params?.[0]?.address?.()` had the mirror-image problem: on Haraka >= 3.2.0 it attempts to call a string (`?.()` only short-circuits on null/undefined, not on non-callables).

## Fix

Extract the bare address through a helper that calls `address` when it is a function and stringifies it otherwise, so the plugin works on either side of the Haraka 3.2.0 parser migration, and guard `in_list` against non-string input so a lookup can never throw. Regression tests exercise all three call sites with real `address-rfc2821` Address objects (added as a devDependency); they fail on the current code and pass with the fix.

### CODE REVIEW

**Comment by msimerson** [comment]
Appreciate the PR, and I know you wouldn't have bothered to create the PR if the change didn't cause an issue for you, but address-rfc282{1,2} are no longer supported (https://github.com/haraka/Haraka/issues/3564). I made a compatibility shim in Haraka itself, a callable function so that Addresses could be called as `host()` or `->host`. I planned a 1-year sunset for that shim but after turning it loose in the wild, it proved problematic because of software that did explicit type checking on `address` or `host`. So I decided it was better to eat the pain all-at-once, leave that issue open for a handful of months, and make it easy for folks to see how to solve the issue. Possible answers:

- install 3.1.7 for legacy Address objects
- install >= 3.2.0 for @haraka/email-address objects

Do you have a use case that is not addressed by either solution?

**Comment by vstakhov** [comment]
Yes, it's mismatch between plugins and Haraka itself (new plugins + older Haraka from docker image). For sure, it there are no backward compatibility guarantee here, then this patch is utterly useless. Feel free to close, I have reworked my docker infra to build the most recent Haraka to avoid that issues in future.
